M48
; DRILL file KiCad 10.0.0-rc1.1 date 2026-02-23T16:24:08
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2026-02-23T16:24:08-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.0-rc1.1
; #@! TF.FileFunction,Plated,1,4,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C0.0394
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.1260
%
G90
G05
T1
X4.1087Y-4.9547
T2
X4.1063Y-3.437
X4.1063Y-5.4055
X6.4685Y-3.437
X6.4685Y-5.4055
M30
